addpath('tests/octave', 'tests/octave/dlm');

%% Multivariate DLM: two sensors observing the same local‑level+trend state
% Model:
%   y(t) = F·x(t) + v, v ~ N(0, diag(V1², V2²))
%   x(t) = G·x(t-1) + w, w ~ N(0, W)
%
% F = [1 0; 1 0]  — both sensors observe the level component only
% G = [1 1; 0 1]  — local linear trend (order=1)
%
% This exercises p=2 with order=1. Both sensors share the same underlying
% state but have different observation noise levels.

disp('Multivariate DLM test: p=2, order=1');

n = 100;

% Deterministic "truth" — simple linear trend + sinusoid
t = (1:n)';
true_level = 50 + 0.3 * t;
true_signal = true_level + 5 * sin(2 * pi * t / 25);

% Deterministic "noise" for reproducibility (no random numbers)
noise1 = 3 * sin(t * 0.73) + 2 * cos(t * 1.17);
noise2 = 5 * sin(t * 0.41) + 4 * cos(t * 0.89);

y1 = true_signal + noise1;   % sensor 1 (lower noise)
y2 = true_signal + noise2;   % sensor 2 (higher noise)

% Stack as n×p matrix (MATLAB DLM convention: y is n rows × p cols)
y = [y1, y2];

% System matrices
p_obs = 2;
m = 2;  % state dim: level + slope

% F: [p, m] — both sensors observe just the level
F = [1, 0; 1, 0];

% V: observation std devs, n×p
s1 = 4;
s2 = 7;
V = repmat([s1, s2], n, 1);  % [n, p]

% G: order=1 local linear trend
G = [1 1; 0 1];

% W: process noise covariance
w = [3, 1];
W = diag(w.^2);

% Initial state
x0 = [mean(y1(1:12)); 0];
c0_val = (abs(x0(1)) * 0.5)^2;
C0 = c0_val * eye(m);

%% Pass 1: diffuse prior (matching dlm-js two-pass procedure)
out1 = dlmsmo(y, F, V, x0, G, W, C0, [], 0, 1, 1);

% Refine initial state from smoothed estimates (matching dlm-js Pass 2)
x0_refined = out1.x(:,1);
C0_refined = out1.C(:,:,1) * 100;

%% Pass 2: refined initial state
out = dlmsmo(y, F, V, x0_refined, G, W, C0_refined, [], 0, 1, 1);

%% Save inputs
inputs = struct( ...
  'y', y, ...       % [n, p]
  'F', F, ...       % [p, m]
  'V', V, ...       % [n, p] obs noise std devs
  's', [s1, s2], ...% [p] scalar obs noise std devs
  'w', w, ...       % process noise std devs
  'G', G, ...       % [m, m]
  'W', W, ...       % [m, m]
  'x0', x0, ...     % [m, 1]
  'C0', C0, ...     % [m, m]
  'x0_refined', x0_refined, ...  % [m, 1]
  'C0_refined', C0_refined, ...  % [m, m]
  'n', n, ...
  'p', p_obs, ...
  'm', m ...
);
save_json(inputs, 'tests/multivariate-in.json');

%% Save outputs
% Smoothed states: x is [m, n] in MATLAB DLM → transpose to [n, m]
% Covariance: C is [m, m, n] → keep as-is (test code handles it)
result = struct( ...
  'x', out.x, ...          % [m, n] smoothed states
  'C', out.C, ...          % [m, m, n] smoothed covariances
  'xf', out.xf, ...        % [m, n] filtered states
  'Cf', out.Cf, ...        % [m, m, n] filtered covariances
  'v', out.v, ...          % [p, n] innovations
  'Cp', out.Cp, ...        % [p, p, n] innovation covariances
  'yhat', out.yhat, ...    % [n, p] filter predictions
  'ystd', out.ystd, ...    % [n, p] prediction std devs
  'resid0', out.resid0, ...% [n, p] raw residuals (y - yhat)
  'resid', out.resid, ...  % [n, p] scaled residuals
  'lik', out.lik, ...      %  -2·logL (scalar)
  's2', out.s2, ...        % residual variance
  'nobs', out.nobs, ...    % [p] number of valid obs per series
  'n', n, ...
  'p', p_obs, ...
  'm', m ...
);
save_json(result, 'tests/multivariate-out-m.json');
disp('  done');

%% Also test p=2 with gapped data (NaN observations)
disp('Multivariate DLM test: p=2, order=1, gapped');

y_gapped = y;
% Introduce NaN gaps — when any component is NaN, entire row is missing
y_gapped(10, :) = NaN;
y_gapped(20, :) = NaN;
y_gapped(30:32, :) = NaN;
y_gapped(50, :) = NaN;

out1_gap = dlmsmo(y_gapped, F, V, x0, G, W, C0, [], 0, 1, 1);
x0_gap = out1_gap.x(:,1);
C0_gap = out1_gap.C(:,:,1) * 100;
out_gap = dlmsmo(y_gapped, F, V, x0_gap, G, W, C0_gap, [], 0, 1, 1);

inputs_gap = struct( ...
  'y', y_gapped, ...
  'F', F, ...
  'V', V, ...
  's', [s1, s2], ...
  'w', w, ...
  'G', G, ...
  'W', W, ...
  'x0', x0, ...
  'C0', C0, ...
  'x0_refined', x0_gap, ...
  'C0_refined', C0_gap, ...
  'n', n, ...
  'p', p_obs, ...
  'm', m ...
);
save_json(inputs_gap, 'tests/multivariate-gapped-in.json');

result_gap = struct( ...
  'x', out_gap.x, ...
  'C', out_gap.C, ...
  'xf', out_gap.xf, ...
  'Cf', out_gap.Cf, ...
  'v', out_gap.v, ...
  'Cp', out_gap.Cp, ...
  'yhat', out_gap.yhat, ...
  'ystd', out_gap.ystd, ...
  'resid0', out_gap.resid0, ...
  'resid', out_gap.resid, ...
  'lik', out_gap.lik, ...
  's2', out_gap.s2, ...
  'nobs', out_gap.nobs, ...
  'n', n, ...
  'p', p_obs, ...
  'm', m ...
);
save_json(result_gap, 'tests/multivariate-gapped-out-m.json');
disp('  done');

%% Test p=2 with order=0 (local level only, simplest multivariate case)
disp('Multivariate DLM test: p=2, order=0');

F_o0 = [1; 1];    % [p, m=1]
G_o0 = [1];        % [1, 1]
W_o0 = [w(1)^2];   % [1, 1]
x0_o0 = [mean(y1(1:12))];
C0_o0 = c0_val * eye(1);

out1_o0 = dlmsmo(y, F_o0, V, x0_o0, G_o0, W_o0, C0_o0, [], 0, 1, 1);
x0_o0r = out1_o0.x(:,1);
C0_o0r = out1_o0.C(:,:,1) * 100;
out_o0 = dlmsmo(y, F_o0, V, x0_o0r, G_o0, W_o0, C0_o0r, [], 0, 1, 1);

inputs_o0 = struct( ...
  'y', y, ...
  'F', F_o0, ...
  'V', V, ...
  's', [s1, s2], ...
  'w', w(1), ...
  'G', G_o0, ...
  'W', W_o0, ...
  'n', n, ...
  'p', p_obs, ...
  'm', 1 ...
);
save_json(inputs_o0, 'tests/multivariate-order0-in.json');

result_o0 = struct( ...
  'x', out_o0.x, ...
  'C', out_o0.C, ...
  'xf', out_o0.xf, ...
  'Cf', out_o0.Cf, ...
  'v', out_o0.v, ...
  'Cp', out_o0.Cp, ...
  'yhat', out_o0.yhat, ...
  'ystd', out_o0.ystd, ...
  'resid0', out_o0.resid0, ...
  'resid', out_o0.resid, ...
  'lik', out_o0.lik, ...
  's2', out_o0.s2, ...
  'nobs', out_o0.nobs, ...
  'n', n, ...
  'p', p_obs, ...
  'm', 1 ...
);
save_json(result_o0, 'tests/multivariate-order0-out-m.json');
disp('  done');

%% Test p=2 with order=1 + AR(2) (trend + autoregression, m=4)
disp('Multivariate DLM test: p=2, order=1, AR(2)');

% Generate system matrices for order=1 + AR(2)
options_ar2 = struct('order', 1, 'arphi', [0.6, -0.3]);
[G_ar2, F_ar2_row] = dlmgensys(options_ar2);
m_ar2 = size(G_ar2, 1);  % should be 4

% F for p=2: both sensors observe level (state 0) and AR component (state 2)
% F_ar2_row = [1, 0, 1, 0] from dlmgensys
F_ar2 = [F_ar2_row; F_ar2_row];  % [2, 4]

% Noise parameters
s1_ar2 = 3;
s2_ar2 = 6;
V_ar2 = repmat([s1_ar2, s2_ar2], n, 1);  % [n, 2]

% Process noise std devs: [level, slope, ar1_state, ar2_state]
w_ar2 = [0.5, 0.05, 2, 0];
W_ar2 = diag(w_ar2.^2);

% Generate deterministic data (trend + AR oscillation + deterministic noise)
ar2_state = zeros(n, 1);
ar2_state(1) = 3;
ar2_state(2) = -1;
for ti = 3:n
  ar2_state(ti) = 0.6 * ar2_state(ti-1) + (-0.3) * ar2_state(ti-2) + 0.5 * sin(ti * 0.37);
end
true_signal_ar2 = true_level + ar2_state;

noise1_ar2 = 3 * sin(t * 0.53) + 2 * cos(t * 1.07);
noise2_ar2 = 6 * sin(t * 0.31) + 4 * cos(t * 0.79);
y1_ar2 = true_signal_ar2 + noise1_ar2;
y2_ar2 = true_signal_ar2 + noise2_ar2;
y_ar2 = [y1_ar2, y2_ar2];

% Initial state
x0_ar2 = [mean(y1_ar2(1:12)); 0; 0; 0];
c0_ar2 = (abs(x0_ar2(1)) * 0.5)^2;
C0_ar2 = c0_ar2 * eye(m_ar2);

% Pass 1: diffuse prior
out1_ar2 = dlmsmo(y_ar2, F_ar2, V_ar2, x0_ar2, G_ar2, W_ar2, C0_ar2, [], 0, 1, 1);

% Pass 2: refined initial state
x0_ar2r = out1_ar2.x(:,1);
C0_ar2r = out1_ar2.C(:,:,1) * 100;
out_ar2 = dlmsmo(y_ar2, F_ar2, V_ar2, x0_ar2r, G_ar2, W_ar2, C0_ar2r, [], 0, 1, 1);

inputs_ar2mv = struct( ...
  'y', y_ar2, ...
  'F', F_ar2, ...
  'V', V_ar2, ...
  's', [s1_ar2, s2_ar2], ...
  'w', w_ar2, ...
  'G', G_ar2, ...
  'W', W_ar2, ...
  'x0', x0_ar2, ...
  'C0', C0_ar2, ...
  'x0_refined', x0_ar2r, ...
  'C0_refined', C0_ar2r, ...
  'n', n, ...
  'p', p_obs, ...
  'm', m_ar2, ...
  'arCoefficients', [0.6, -0.3] ...
);
save_json(inputs_ar2mv, 'tests/multivariate-ar2-in.json');

result_ar2mv = struct( ...
  'x', out_ar2.x, ...
  'C', out_ar2.C, ...
  'xf', out_ar2.xf, ...
  'Cf', out_ar2.Cf, ...
  'v', out_ar2.v, ...
  'Cp', out_ar2.Cp, ...
  'yhat', out_ar2.yhat, ...
  'ystd', out_ar2.ystd, ...
  'resid0', out_ar2.resid0, ...
  'resid', out_ar2.resid, ...
  'lik', out_ar2.lik, ...
  's2', out_ar2.s2, ...
  'nobs', out_ar2.nobs, ...
  'n', n, ...
  'p', p_obs, ...
  'm', m_ar2 ...
);
save_json(result_ar2mv, 'tests/multivariate-ar2-out-m.json');
disp('  done');
