/**
 * Multivariate observation (p > 1) tests.
 *
 * Verifies that dlm-js correctly handles vector observations by comparing
 * against Octave reference output generated by tests/octave/multivariate_demo.m.
 *
 * Three test cases:
 *   1. p=2, order=1 (local linear trend, m=2): two sensors observe the level
 *   2. p=2, order=1, gapped (NaN at selected timesteps): joint NaN masking
 *   3. p=2, order=0 (local level, m=1): simplest multivariate case
 *
 * Keys compared: x (smoothed states), yhat, ystd, lik, nobs.
 * v and Cp are also checked but with layout conversion (Octave → JS flat).
 */
import { describe, it, expect } from 'vitest';
import { dlmFit, toMatlab } from '../src/index';
import type { DlmAlgorithm } from '../src/types';
import { deepAlmostEqual, normalizeNulls, normalizeMatlabOutput } from './utils';
import { getTestConfigs, applyConfig, getDlmDtype, getModelTolerances, type TestConfig } from './test-matrix';
import * as fs from 'fs';
import * as path from 'path';

// ── Reference file helpers ─────────────────────────────────────────────────

function loadPair(inFile: string, outFile: string) {
  if (!fs.existsSync(inFile))  throw new Error(`Input file not found: ${inFile} — run Octave multivariate_demo.m`);
  if (!fs.existsSync(outFile)) throw new Error(`Reference file not found: ${outFile} — run Octave multivariate_demo.m`);
  const inp = JSON.parse(fs.readFileSync(inFile, 'utf-8')) as Record<string, unknown>;
  const ref = normalizeNulls(
    JSON.parse(fs.readFileSync(outFile, 'utf-8'))
  ) as Record<string, unknown>;
  return { inp, ref };
}

/**
 * Flatten an Octave [n, p] array to [n*p] row-major for comparison with JS output.
 */
function flattenNP(arr: number[][]): number[] {
  const flat: number[] = [];
  for (const row of arr) {
    for (const v of row) flat.push(v);
  }
  return flat;
}

/**
 * Reorder Octave Cp [p, p, n] to flat [n*p*p] row-major to match JS layout.
 * Octave: Cp[i][j][t], JS: flat[t*p*p + i*p + j]
 */
function reorderCp(Cp: number[][][], n: number, p: number): number[] {
  const flat = new Array<number>(n * p * p);
  for (let t = 0; t < n; t++) {
    for (let i = 0; i < p; i++) {
      for (let j = 0; j < p; j++) {
        flat[t * p * p + i * p + j] = Cp[i][j][t];
      }
    }
  }
  return flat;
}

// ── Test runner ───────────────────────────────────────────────────────────

const runMultivariateTest = async (
  config: TestConfig,
  inp: Record<string, unknown>,
  ref: Record<string, unknown>,
  label: string,
  compareFilterDiag = true,
  algorithm?: DlmAlgorithm,
) => {
  applyConfig(config);

  const n = inp['n'] as number;
  const p = inp['p'] as number;
  const m = inp['m'] as number;

  // Get appropriate tolerances — p>1 may have wider drift on f32
  const tol = getModelTolerances(config, m);

  // Build observation matrix F: [p, m]
  const F_raw = inp['F'] as number[] | number[][];
  const F: number[][] = Array.isArray(F_raw[0])
    ? F_raw as number[][]
    : (F_raw as number[]).map(v => [v]);  // column vector [p,1] for m=1

  // obsStd from input: s is [p] scalar Per-component std devs → diagonal
  const s_arr = inp['s'] as number[];

  // Process noise std devs
  const w_raw = inp['w'];
  const w: number[] = typeof w_raw === 'number' ? [w_raw] : w_raw as number[];

  // Infer order from state dimension (m=1 → order=0, m=2 → order=1)
  const order = m === 1 ? 0 : m - 1;

  // y as number[][] (n rows × p cols)
  const y_raw = inp['y'] as (number | null)[][];
  const y: number[][] = y_raw.map(row => row.map(v => v === null ? NaN : v));

  const result = await dlmFit(y, {
    obsStd: s_arr,
    processStd: w,
    F,
    order,
    dtype: getDlmDtype(config),
    ...(algorithm ? { algorithm } : {}),
  });

  const matlab = toMatlab(result);

  const outDir = path.join(__dirname, 'out');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const outputFileName = path.join(outDir,
    `multivariate-${label}-${config.label.replace('/', '-')}.json`);
  fs.writeFileSync(outputFileName, JSON.stringify(matlab, (_key, value) =>
    ArrayBuffer.isView(value) ? Array.from(value as Float64Array) : value
  , 2));

  // ── Basic shape checks ─────────────────────────────────────────────────
  expect(matlab.p).toBe(p);
  expect(matlab.m).toBe(m);
  expect(matlab.n).toBe(n);

  // ── nobs: JS returns scalar (valid timesteps), Octave returns [p] ────
  const refNobs = ref['nobs'] as number[];
  expect(matlab.nobs).toBe(refNobs[0]);

  // ── Likelihood (scalar) ──────────────────────────────────────────────
  if (tol) {
    const refLik = ref['lik'] as number;
    const likCmp = deepAlmostEqual(matlab.lik, refLik, tol.relativeTolerance, 'lik', tol.absoluteTolerance);
    if (!likCmp.equal) {
      throw new Error(`[${config.label}] ${label}: lik mismatch — got ${matlab.lik}, expected ${refLik}`);
    }
  }

  // ── State estimates: x [m][n], C [m][m][n] via toMatlab ──────────────
  if (tol) {
    const normalizedRef = normalizeMatlabOutput(ref, m);

    // Compare smoothed states x[m][n]
    const xCmp = deepAlmostEqual(
      matlab.x.map(a => Array.from(a)),
      normalizedRef['x'],
      tol.relativeTolerance, 'x', tol.absoluteTolerance
    );
    if (!xCmp.equal) {
      throw new Error(
        `[${config.label}] ${label}: x mismatch at ${xCmp.path}\n` +
        `  got: ${JSON.stringify(xCmp.a)}\n  expected: ${JSON.stringify(xCmp.b)}`
      );
    }

    // Compare smoothed covariances C[m][m][n]
    const cCmp = deepAlmostEqual(
      matlab.C.map(row => row.map(a => Array.from(a))),
      normalizedRef['C'],
      tol.relativeTolerance, 'C', tol.absoluteTolerance
    );
    if (!cCmp.equal) {
      throw new Error(
        `[${config.label}] ${label}: C mismatch at ${cCmp.path}\n` +
        `  got: ${JSON.stringify(cCmp.a)}\n  expected: ${JSON.stringify(cCmp.b)}`
      );
    }
  }

  // ── Observation-space diagnostics: flat [n*p] ────────────────────────
  if (tol) {
    // yhat
    const refYhat = flattenNP(ref['yhat'] as number[][]);
    const yhatCmp = deepAlmostEqual(
      Array.from(matlab.yhat), refYhat,
      tol.relativeTolerance, 'yhat', tol.absoluteTolerance
    );
    if (!yhatCmp.equal) {
      throw new Error(
        `[${config.label}] ${label}: yhat mismatch at ${yhatCmp.path}\n` +
        `  got: ${JSON.stringify(yhatCmp.a)}\n  expected: ${JSON.stringify(yhatCmp.b)}`
      );
    }

    // ystd
    const refYstd = flattenNP(ref['ystd'] as number[][]);
    const ystdCmp = deepAlmostEqual(
      Array.from(matlab.ystd), refYstd,
      tol.relativeTolerance, 'ystd', tol.absoluteTolerance
    );
    if (!ystdCmp.equal) {
      throw new Error(
        `[${config.label}] ${label}: ystd mismatch at ${ystdCmp.path}\n` +
        `  got: ${JSON.stringify(ystdCmp.a)}\n  expected: ${JSON.stringify(ystdCmp.b)}`
      );
    }

    // innovations v and Cp — skip for gapped data where initial state differs
    if (compareFilterDiag) {
      const refV = flattenNP(ref['v'] as number[][]);
      const vCmp = deepAlmostEqual(
        Array.from(matlab.v), refV,
        tol.relativeTolerance, 'v', tol.absoluteTolerance
      );
      if (!vCmp.equal) {
        throw new Error(
          `[${config.label}] ${label}: v mismatch at ${vCmp.path}\n` +
          `  got: ${JSON.stringify(vCmp.a)}\n  expected: ${JSON.stringify(vCmp.b)}`
        );
      }

      const refCp = reorderCp(ref['Cp'] as number[][][], n, p);
      const cpCmp = deepAlmostEqual(
        Array.from(matlab.Cp), refCp,
        tol.relativeTolerance, 'Cp', tol.absoluteTolerance
      );
      if (!cpCmp.equal) {
        throw new Error(
          `[${config.label}] ${label}: Cp mismatch at ${cpCmp.path}\n` +
          `  got: ${JSON.stringify(cpCmp.a)}\n  expected: ${JSON.stringify(cpCmp.b)}`
        );
      }
    }
  }

  // ── Smoke test (f32 + large m): all outputs finite ───────────────────
  if (!tol) {
    expect(Array.from(matlab.yhat).every(v => isFinite(v))).toBe(true);
    expect(Array.from(matlab.ystd).every(v => isFinite(v) && v > 0)).toBe(true);
    expect(isFinite(matlab.lik)).toBe(true);
  }
};

// ── Load test data ─────────────────────────────────────────────────────────

const inFile1   = path.join(__dirname, 'multivariate-in.json');
const refFile1  = path.join(__dirname, 'multivariate-out-m.json');
const inFile2   = path.join(__dirname, 'multivariate-gapped-in.json');
const refFile2  = path.join(__dirname, 'multivariate-gapped-out-m.json');
const inFile3   = path.join(__dirname, 'multivariate-order0-in.json');
const refFile3  = path.join(__dirname, 'multivariate-order0-out-m.json');

const { inp: inp1, ref: ref1 } = loadPair(inFile1, refFile1);
const { inp: inp2, ref: ref2 } = loadPair(inFile2, refFile2);
const { inp: inp3, ref: ref3 } = loadPair(inFile3, refFile3);

// ── Test suites ────────────────────────────────────────────────────────────

describe('multivariate (p=2) — order=1 (m=2)', async () => {
  const configs = await getTestConfigs();

  for (const config of configs) {
    it(`should match Octave reference (${config.label})`, async () => {
      await runMultivariateTest(config, inp1, ref1, 'order1');
    });

    it(`should match Octave reference — 2nd run (${config.label})`, async () => {
      await runMultivariateTest(config, inp1, ref1, 'order1');
    });
  }
});

describe('multivariate (p=2) — order=1, gapped (m=2)', async () => {
  const configs = await getTestConfigs();

  for (const config of configs) {
    it(`should match Octave reference (${config.label})`, async () => {
      // Skip v/Cp: Octave reference uses non-gapped x0; dlmFit derives x0 from gapped y
      await runMultivariateTest(config, inp2, ref2, 'gapped', false);
    });

    it(`should match Octave reference — 2nd run (${config.label})`, async () => {
      await runMultivariateTest(config, inp2, ref2, 'gapped', false);
    });
  }
});

describe('multivariate (p=2) — order=0 (m=1)', async () => {
  const configs = await getTestConfigs();

  for (const config of configs) {
    it(`should match Octave reference (${config.label})`, async () => {
      await runMultivariateTest(config, inp3, ref3, 'order0');
    });

    it(`should match Octave reference — 2nd run (${config.label})`, async () => {
      await runMultivariateTest(config, inp3, ref3, 'order0');
    });
  }
});

// ── Associative scan (algorithm: 'assoc') — f64 only ───────────────────────

describe('multivariate assoc (p=2) — order=1 (m=2)', async () => {
  const configs = await getTestConfigs();
  const f64Configs = configs.filter(c => c.label.includes('f64'));

  for (const config of f64Configs) {
    it(`should match Octave reference (${config.label})`, async () => {
      await runMultivariateTest(config, inp1, ref1, 'order1-assoc', true, 'assoc');
    });

    it(`should match Octave reference — 2nd run (${config.label})`, async () => {
      await runMultivariateTest(config, inp1, ref1, 'order1-assoc', true, 'assoc');
    });
  }
});

describe('multivariate assoc (p=2) — order=1, gapped (m=2)', async () => {
  const configs = await getTestConfigs();
  const f64Configs = configs.filter(c => c.label.includes('f64'));

  for (const config of f64Configs) {
    it(`should match Octave reference (${config.label})`, async () => {
      await runMultivariateTest(config, inp2, ref2, 'gapped-assoc', false, 'assoc');
    });

    it(`should match Octave reference — 2nd run (${config.label})`, async () => {
      await runMultivariateTest(config, inp2, ref2, 'gapped-assoc', false, 'assoc');
    });
  }
});

describe('multivariate assoc (p=2) — order=0 (m=1)', async () => {
  const configs = await getTestConfigs();
  const f64Configs = configs.filter(c => c.label.includes('f64'));

  for (const config of f64Configs) {
    it(`should match Octave reference (${config.label})`, async () => {
      await runMultivariateTest(config, inp3, ref3, 'order0-assoc', true, 'assoc');
    });

    it(`should match Octave reference — 2nd run (${config.label})`, async () => {
      await runMultivariateTest(config, inp3, ref3, 'order0-assoc', true, 'assoc');
    });
  }
});
